footprint: [[0.7, 0.35], [-0.70, 0.35], [-0.70, -0.35], [0.70, -0.35]]
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
